### ISSUE TITLE
Database objects are still deleted after disconnection

### ISSUE THREAD

**Issue by dongfo** [tomasfabian/SqlTableDependency.Extensions#1]
Database objects are still deleted after disconnection。
Infomation of data change still lost between disconnection time.

**Comment by tfabian** [comment]
Hi @dongfo.
the database objects are deleted intentionally, so the queues don't grow "infinitelly"(constrained by resources). SqlTableDependency doesn't allow to reuse previous database objects.

After reconnection you should refresh your data, in the same way as you did at the beginning with initial data, but clear the old data before it or synchronize them. You can subscribe to WhenStatusChanges and do it based on enum value TableDependencyStatus.Started.

I can provide an example later. Let me know what do you think.

Thx, Tomas

**Comment by tfabian** [comment]
> Database objects are still deleted after disconnection。
> Infomation of data change still lost between disconnection time.

Hi @**dongfo**.
I pushed a beta version which reconnects to an existing conversation handler within the timeout period. Could you try it, please?

Thank you in advance, Tomas.

**Comment by tomasfabian** [comment]
Hi,
version 2.0 has been just released. There are 2 new lifetime scopes. I hope you will enjoy them.

Tomas Fabian
