### ISSUE TITLE
Not Throwing an Exception when StringConnection is wrong or the Broker is not enabled

### ISSUE THREAD

**Issue by nadjibnet** [tomasfabian/SqlTableDependency.Extensions#2]
Hello,

I'm the same person that reported before on the topic:
[SqlTableDependency Recover Connection (Reconnecting)](https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/issues/95) 

First, I'm happy that I was the origin of your contribution, I want to thank you for this nice work.

I just have tested it right now, and I want to inform you that using the basic usage, if something is wrong on StringConnection or the  Service Broker is not enabled, we didn't get an exception, it just not give up an notification.

Thank you again for this nice work.

**Comment by tfabian** [comment]
Hi **@nadjibnet** 
I'm glad that I could help you.
I have just tried a connection string with a typo and I received an error message "_Impossible open db connection using the following connection string_" in the overridden method OnError:

```
    protected override void OnError(Exception exception)
    {
      base.OnError(exception);
```

Empty connection string throws System.ArgumentNullException: 'Value cannot be null. (Parameter 'connectionString')'

In case that the Service broker wasn't enabled I received the following error "_Service broker not enable. Please activete it using 'ALTER DATABASE MyDatabase SET ENABLE_BROKER' command_."

Tomas

**Comment by tomasfabian** [comment]
As far as I know the throwing of above mentioned exceptions should be right
