### ISSUE TITLE
There is no way to mention the schema name. 

### ISSUE THREAD

**Issue by RajathVenkatesh** [tomasfabian/SqlTableDependency.Extensions#3]
Great work on this extension, keep it going. 

With the sqltabledependency constructor I could pass the schema name of the table as a parameter. This seems to not be possible with the sqltabledependencyprovider abstract class. 

I may be wrong, please can you suggest a way to do this?

**Comment by tomasfabian** [comment]
Hi @RajathVenkatesh,
thank you very much for your appretiation. 
I pushed a new version 2.1 to nuget which enables you to set these additional settings in this way:
```

    protected override SqlTableDependencySettings<TEntity> OnCreateSettings()
    {
      var settings =  base.OnCreateSettings();

      settings.SchemaName = "dbo";

      return settings;
    }

  public class SqlTableDependencySettings<TEntity> 
    where TEntity : class
  {
    public string SchemaName { get; set; }
    public IUpdateOfModel<TEntity> UpdateOf { get; set; }
    public ITableDependencyFilter Filter { get; set; }
    public DmlTriggerType NotifyOn { get; set; } = DmlTriggerType.All;
    public bool ExecuteUserPermissionCheck { get; set; } = true;
    public bool IncludeOldValues { get; set; }
  }
```

Tomas

**Comment by RajathVenkatesh** [comment]
Thanks a ton Tomas. Works like a charm!

I was using the sqltabledependency class in my development and ran into problems of deleted sql objects during reconnections(network issues) and server shut downs. 
This reactive extension looks like a very suitable solution and I will be using it for the rest of my development, you could hear from me in the next couple of days again if I run into any other problems. 

Closing this thread.
