### ISSUE TITLE
Calling dispose method on the provider does not dispose all of the sql table dependency objects immediately 

### ISSUE THREAD

**Issue by RajathVenkatesh** [tomasfabian/SqlTableDependency.Extensions#4]
Hi

The sql server objects need to get disposed immediately when I call the dispose method from the application, this does not seem to work at all and it looks like it waits for the watch dog to do the clean up instead. Please can I get some insight on this please?

Rajath

**Comment by tomasfabian** [comment]
Hi @RajathVenkatesh,
which LifetimeScope do you use? UniqueScope does not drop database objects on disposal. Could you try Application scope? Please have a look at readme.md.

```C#
  public enum LifetimeScope
  {
    ConnectionScope = 1,
    UniqueScope = 2,
    ApplicationScope = 3
  }
```

Tomas

**Comment by RajathVenkatesh** [comment]
@tomasfabian 
Sort of knew this was the problem, apologise for not giving it a try. (I guess I had misunderstood the Readme)

I have switched it to the application scope lifetime and the sql objects gets disposed immediately now on calling the dispose method. 
Thank you. 

Rajath
