### ISSUE TITLE
Getting old values with an update event

### ISSUE THREAD

**Issue by tzepterbvv** [tomasfabian/SqlTableDependency.Extensions#6]
In that moment it is not possible to get the former data row state during an OnUpdate event, even if the IncludeOldValues settings attribute is set true. Is it possible to fix that?

**Comment by tomasfabian** [comment]
Hi @tzepterbvv,
I released SqlTableDependency.Extensions 2.3.0 with the enhancement for old values.

For the following setting:
`settings.IncludeOldValues = true;`

I added a new argument to SqlTableDependencyProvider.OnUpdated
`OnUpdated(TEntity entity, TEntity entityOldValues)`

and `RecordChangedNotification<TEntity>.EntityOldValues` propagated from `SqlTableDependencyProvider.WhenEntityRecordChanges`

Regards, Tomas

**Comment by tzepterbvv** [comment]
Hi Tomas, 2.3.0 works fine as expected. Thanks, Tobi
