### ISSUE TITLE
Read the DB-Attributes out of the TableAttribute

### ISSUE THREAD

**Issue by tzepterbvv** [tomasfabian/SqlTableDependency.Extensions#7]
Hi Tomas,

I use Extensions 2.3 and it works fine if I override the attribute TableName within the SqlTableDependencyProvider<> derivate with the real table name respectively the settings.SchemaName with the real schema name, because my Entity-class is named different to the table name because of different convention (camel case vs. big case, English vs. German).

I used before the original SqlTableDependency. There it was possibe to define the table and schema and column namnes as attributes in the entity class. This brings all definition at one location together. Could you implement it for the Extensions, too?

Thx,
Tobi

**Comment by tomasfabian** [comment]
Hi Tobi,
I added support for TableAttribute in version 2.3.1.

Regards Tomas

**Comment by tzepterbvv** [comment]
Thank you, Tomas. Works great!
